/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spark.pilot;

import static spark.Spark.*;

import java.io.InputStream;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

import org.javalite.activejdbc.Base;

public class App {
    public static void main(String[] args) {
        App.app();
    }

    public static void app() {
        HikariConfig config = new HikariConfig("/hikari.properties");
        HikariDataSource ds = new HikariDataSource(config);

        before((req, res) -> {
            Base.open(ds);
        });

        get("/", (req, res) -> {
            return User.findAll().toJson(true);
        });

        after((req, res) -> {
            Base.close();
        });
    }
}
